version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_DATABASE: brackets
      MYSQL_USER: brackets
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:alpine
    restart: always

  web:
    depends_on:
      - db
      - redis
    build: .
    ports:
      - "5000:80"
    restart: always
volumes:
  mysql_data: {}
